env: "local" # local, dev, prod
storage_path: "postgress://postgress:root@localhost:5432:Phonebook"
http_serer:
  adress: "localhist:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser1"
  password: "mypass1"